#Ce fichier lance le clone de S3

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              value: "minioadmin"
          ports:
            - containerPort: 9000 # API S3
            - containerPort: 9001 # Console Web
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: default
spec:
  type: NodePort  # <--- LE CHANGEMENT EST ICI
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30090  # On fixe le port 30090 pour l'API
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30091  # On fixe le port 30091 pour l'interface Web